[manager]
show_hidden = true
sort_by = "natural"
sort_reverse = false
sort_dir_first = true

[plugin]
prepend_previewers = [
	{ name = "*.tsp" , run = "bat" },
]

[[plugin.prepend_fetchers]]
id   = "git"
name = "*"
run  = "git"

[[plugin.prepend_fetchers]]
id   = "git"
name = "*/"
run  = "git"
